image: nodejs

services:
    - docker:dind

stages:
    - deploy
    - publish

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

deploy:
    stage: deploy
    tags:
        - deploying
    script:
        - docker container stop -f laruno-api || true && docker container rm -f laruno-api || true
        - docker image rm laruno/laruno-api || true
        - cat package.json
        - echo "Building image.."
        - docker build -t laruno/laruno-api --no-cache .
    only:
        - master

publish:
    stage: publish
    tags:
        - publishing
    script:
        #- docker container stop -f laruno-api || true && docker container rm -f laruno-api || true
        - docker run --name laruno-api -p 8000:8000 -d laruno/laruno-api
        - docker container prune -f
        - docker image prune -f
    only:
        - master
