
FROM nginx:alpine
#COPY ./nginx-conf/api.laruno.id /etc/nginx/sites-available/
COPY ./nginx-conf/nginx.conf /etc/nginx/nginx.conf
#COPY ./nginx-conf/default.conf /etc/nginx/conf.d/ # Copy nginx configuration file
#COPY default.conf /etc/nginx/conf.d/default.conf